"""
DNS Control — Runtime Inventory Service
Discovers infrastructure from the running system without depending on
naming conventions or deploy artifacts generated by the DNS Control wizard.

Sources:
  - systemctl: discover unbound instances
  - /etc/unbound/*.conf: extract bind IPs, control interfaces/ports
  - ip -j addr show: discover VIPs on loopback
  - nft -j list ruleset: discover DNAT rules and sticky sets
  - ss -tulnp: discover DNS listeners

This service is the foundation of "observed" mode, allowing the dashboard
to function on manually configured hosts.
"""

import json
import re
import logging
from datetime import datetime, timezone

from app.executors.command_runner import run_command

logger = logging.getLogger("dns-control.runtime-inventory")


def _safe_run(executable: str, args: list[str], timeout: int = 10, use_privilege: bool = False) -> dict:
    try:
        return run_command(executable, args, timeout=timeout, use_privilege=use_privilege)
    except Exception as e:
        logger.debug(f"Command {executable} failed: {e}")
        return {"exit_code": -1, "stdout": "", "stderr": str(e), "duration_ms": 0}


# ── Unbound instance discovery ──────────────────────────────


def discover_unbound_instances() -> list[dict]:
    """
    Discover ALL unbound instances from systemd (running or loaded).
    For each, parse config to extract bind IPs, control interface/port.
    Returns list of dicts compatible with dns_instances table schema.
    """
    result = _safe_run(
        "systemctl", ["list-units", "--all", "--type=service", "--no-pager", "--plain"],
        timeout=10,
    )
    instances = []
    if result["exit_code"] != 0:
        return instances

    for line in result["stdout"].split("\n"):
        if "unbound" not in line or ".service" not in line:
            continue
        name = line.split()[0].replace(".service", "").lstrip("●").strip()
        if name == "unbound":
            continue  # Skip generic service

        is_running = "running" in line or ("active" in line and "inactive" not in line)
        config = _parse_unbound_config(name)

        instances.append({
            "instance_name": name,
            "bind_ips": config["bind_ips"],
            "bind_ip": config["bind_ips"][0] if config["bind_ips"] else "127.0.0.1",
            "bind_port": config["port"],
            "control_interface": config["control_interface"],
            "control_port": config["control_port"],
            "outgoing_ips": config["outgoing_ips"],
            "outgoing_ip": config["outgoing_ips"][0] if config["outgoing_ips"] else None,
            "is_running": is_running,
            "config_path": config["config_path"],
        })

    return instances


def _parse_unbound_config(instance_name: str) -> dict:
    """Parse unbound config for bind IPs, control interface/port, outgoing IPs."""
    config_path = f"/etc/unbound/{instance_name}.conf"
    result = _safe_run("cat", [config_path], timeout=5)

    config = {
        "bind_ips": [],
        "port": 53,
        "control_interface": "127.0.0.1",
        "control_port": 8953,
        "outgoing_ips": [],
        "config_path": config_path,
    }

    if result["exit_code"] != 0:
        return config

    for line in result["stdout"].split("\n"):
        stripped = line.strip()
        if stripped.startswith("#"):
            continue

        if stripped.startswith("interface:") and not stripped.startswith("interface-automatic"):
            ip = stripped.split(":", 1)[1].strip()
            # Handle interface with port: 10.0.0.1@5353
            if "@" in ip:
                parts = ip.split("@")
                ip = parts[0]
                try:
                    config["port"] = int(parts[1])
                except ValueError:
                    pass
            if ip and not ip.startswith("#"):
                config["bind_ips"].append(ip)

        elif stripped.startswith("port:"):
            try:
                config["port"] = int(stripped.split(":", 1)[1].strip())
            except ValueError:
                pass

        elif stripped.startswith("control-interface:"):
            config["control_interface"] = stripped.split(":", 1)[1].strip()

        elif stripped.startswith("control-port:"):
            try:
                config["control_port"] = int(stripped.split(":", 1)[1].strip())
            except ValueError:
                pass

        elif stripped.startswith("outgoing-interface:"):
            ip = stripped.split(":", 1)[1].strip()
            if ip:
                config["outgoing_ips"].append(ip)

    if not config["bind_ips"]:
        config["bind_ips"] = ["127.0.0.1"]

    return config


# ── VIP discovery from loopback ─────────────────────────────


def discover_vips() -> list[dict]:
    """
    Discover VIPs from loopback interfaces (lo, lo0, lo:*, dummy*).
    Returns IPs with /32 mask that are not 127.0.0.1.
    """
    result = _safe_run("ip", ["-j", "addr", "show"], timeout=5)
    vips = []

    if result["exit_code"] != 0:
        return vips

    try:
        interfaces = json.loads(result["stdout"])
    except (json.JSONDecodeError, ValueError):
        return vips

    for iface in interfaces:
        ifname = iface.get("ifname", "")
        # Include loopback and dummy interfaces
        if not (ifname == "lo" or ifname.startswith("lo") or ifname.startswith("dummy")):
            continue

        for addr in iface.get("addr_info", []):
            if addr.get("family") != "inet":
                continue
            ip = addr.get("local", "")
            prefixlen = addr.get("prefixlen", 0)
            if ip == "127.0.0.1":
                continue
            if ip:
                vips.append({
                    "ip": ip,
                    "prefixlen": prefixlen,
                    "interface": ifname,
                    "label": addr.get("label", ifname),
                })

    return vips


# ── DNAT discovery from nftables ────────────────────────────


def discover_dnat_rules() -> list[dict]:
    """
    Discover all DNAT rules from nftables ruleset.
    Name-agnostic: detects by 'dnat to' keyword, not chain names.
    Also detects vmap-based DNAT (numgen ... vmap { ... } dnat).
    Returns list of DNAT mappings with counters.
    """
    result = _safe_run("nft", ["list", "ruleset"], timeout=10, use_privilege=True)
    if result["exit_code"] != 0:
        logger.warning(f"nft list ruleset failed (exit={result['exit_code']}): {result.get('stderr', '')[:200]}")
        return []

    rules = []
    current_chain = ""
    current_table = ""

    ruleset_text = result["stdout"]

    for line in ruleset_text.split("\n"):
        stripped = line.strip()

        table_match = re.match(r'table\s+(\S+)\s+(\S+)\s*\{', stripped)
        if table_match:
            current_table = f"{table_match.group(1)} {table_match.group(2)}"
            continue

        chain_match = re.match(r'chain\s+(\S+)\s*\{', stripped)
        if chain_match:
            current_chain = chain_match.group(1)
            continue

        if "dnat" not in stripped:
            continue

        # Extract counters (present on both simple and vmap rules)
        counter_match = re.search(r'counter packets (\d+) bytes (\d+)', stripped)
        packets = int(counter_match.group(1)) if counter_match else 0
        bytes_val = int(counter_match.group(2)) if counter_match else 0

        # Extract destination IP (VIP) from the rule
        dest_ip = None
        dest_match = re.search(r'ip\s+daddr\s+(\d+\.\d+\.\d+\.\d+)', stripped)
        if dest_match:
            dest_ip = dest_match.group(1)
        dest_set_match = re.search(r'ip\s+daddr\s+\{([^}]+)\}', stripped)
        dest_ips = []
        if dest_set_match:
            dest_ips = [ip.strip() for ip in dest_set_match.group(1).split(",") if ip.strip()]

        # Detect protocol
        proto = "unknown"
        if re.search(r'\btcp\s+dport\b|\bmeta\s+l4proto\s+tcp\b', stripped):
            proto = "tcp"
        elif re.search(r'\budp\s+dport\b|\bmeta\s+l4proto\s+udp\b', stripped):
            proto = "udp"

        # Pattern 1: simple "dnat to IP:PORT"
        dnat_match = re.search(r'dnat to (\d+\.\d+\.\d+\.\d+)(?::(\d+))?', stripped)
        if dnat_match:
            backend_ip = dnat_match.group(1)
            backend_port = int(dnat_match.group(2)) if dnat_match.group(2) else 53
            rules.append({
                "backend_ip": backend_ip,
                "backend_port": backend_port,
                "dest_ip": dest_ip,
                "dest_ips": dest_ips if dest_ips else ([dest_ip] if dest_ip else []),
                "protocol": proto,
                "packets": packets,
                "bytes": bytes_val,
                "chain": current_chain,
                "table": current_table,
                "raw_rule": stripped[:200],
            })
            continue

        # Pattern 2: vmap-based DNAT "dnat to ... vmap { 0 : IP, 1 : IP }"
        # or "numgen ... vmap { 0 : IP:PORT, ... }"
        vmap_match = re.search(r'vmap\s*\{([^}]+)\}', stripped)
        if vmap_match and "dnat" in stripped:
            vmap_content = vmap_match.group(1)
            for entry in vmap_content.split(","):
                entry = entry.strip()
                ip_match = re.search(r'(\d+\.\d+\.\d+\.\d+)(?::(\d+))?', entry)
                if ip_match:
                    backend_ip = ip_match.group(1)
                    backend_port = int(ip_match.group(2)) if ip_match.group(2) else 53
                    rules.append({
                        "backend_ip": backend_ip,
                        "backend_port": backend_port,
                        "dest_ip": dest_ip,
                        "dest_ips": dest_ips if dest_ips else ([dest_ip] if dest_ip else []),
                        "protocol": proto,
                        "packets": packets,
                        "bytes": bytes_val,
                        "chain": current_chain,
                        "table": current_table,
                        "raw_rule": stripped[:200],
                    })

    rules.extend(_discover_nft_daddr_dnat_correlations(ruleset_text))

    logger.info(f"DNAT discovery: found {len(rules)} rules")
    return rules


def _extract_nft_dnat_targets(rule_line: str) -> list[dict]:
    """Extract literal DNAT backends from one nftables rule line."""
    targets = []
    seen = set()

    for match in re.finditer(r'\bdnat\s+to\s+(\d+\.\d+\.\d+\.\d+)(?::(\d+))?', rule_line):
        ip = match.group(1)
        port = int(match.group(2)) if match.group(2) else 53
        key = (ip, port)
        if key not in seen:
            seen.add(key)
            targets.append({"backend_ip": ip, "backend_port": port})

    for match in re.finditer(r'\bdnat\s+to\s+\[([0-9A-Fa-f:.]+)\](?::(\d+))?', rule_line):
        ip = match.group(1)
        port = int(match.group(2)) if match.group(2) else 53
        key = (ip, port)
        if key not in seen:
            seen.add(key)
            targets.append({"backend_ip": ip, "backend_port": port})

    for match in re.finditer(r'\bdnat\s+to\s+([0-9A-Fa-f:]{2,})(?:\s|$)', rule_line):
        ip = match.group(1)
        key = (ip, 53)
        if key not in seen:
            seen.add(key)
            targets.append({"backend_ip": ip, "backend_port": 53})

    return targets


def _extract_nft_jump_targets(rule_line: str) -> list[str]:
    """Extract jump/goto chain targets from an nftables rule line."""
    return [m.group(1) for m in re.finditer(r'\b(?:jump|goto)\s+([A-Za-z0-9_.:-]+)\b', rule_line)]


def _extract_nft_capture_destinations(rule_line: str) -> list[str]:
    """Extract literal ip/ip6 daddr values from capture rules only."""
    dests = []

    for match in re.finditer(r'\bip\s+daddr\s+(\d+\.\d+\.\d+\.\d+)\b', rule_line):
        dests.append(match.group(1))
    for match in re.finditer(r'\bip6\s+daddr\s+([0-9A-Fa-f:]+)\b', rule_line):
        dests.append(match.group(1))

    for match in re.finditer(r'\bip\s+daddr\s+\{([^}]+)\}', rule_line):
        for token in re.split(r'[,\s]+', match.group(1)):
            token = token.strip()
            if re.fullmatch(r'\d+\.\d+\.\d+\.\d+', token):
                dests.append(token)
    for match in re.finditer(r'\bip6\s+daddr\s+\{([^}]+)\}', rule_line):
        for token in re.split(r'[,\s]+', match.group(1)):
            token = token.strip()
            if re.fullmatch(r'[0-9A-Fa-f:]+', token) and ':' in token:
                dests.append(token)

    deduped = []
    seen = set()
    for dest in dests:
        if dest not in seen:
            seen.add(dest)
            deduped.append(dest)
    return deduped


def _index_nft_chains(ruleset_text: str) -> dict:
    """Build a table-local chain index from text `nft list ruleset` output."""
    tables: dict = {}
    current_table = ""
    current_chain = ""
    chain_depth = 0

    for line in ruleset_text.split("\n"):
        stripped = line.strip()
        if not stripped:
            continue

        table_match = re.match(r'table\s+(\S+)\s+(\S+)\s*\{', stripped)
        if table_match and not current_chain:
            current_table = f"{table_match.group(1)} {table_match.group(2)}"
            tables.setdefault(current_table, {})
            continue

        chain_match = re.match(r'chain\s+(\S+)\s*\{', stripped)
        if chain_match:
            current_chain = chain_match.group(1)
            tables.setdefault(current_table, {}).setdefault(current_chain, [])
            inline_body = stripped.split("{", 1)[1].strip()
            if inline_body and inline_body != "}":
                inline_body = inline_body.rsplit("}", 1)[0].strip()
                if inline_body:
                    tables[current_table][current_chain].append(inline_body)
            chain_depth = stripped.count("{") - stripped.count("}")
            if chain_depth <= 0:
                current_chain = ""
            continue

        if current_chain:
            tables.setdefault(current_table, {}).setdefault(current_chain, []).append(stripped)
            chain_depth += stripped.count("{") - stripped.count("}")
            if chain_depth <= 0:
                current_chain = ""

    return tables


def _discover_nft_daddr_dnat_correlations(ruleset_text: str) -> list[dict]:
    """
    Correlate expanded nftables capture rules with DNAT action chains.

    Runtime `nft list ruleset` expands `define DNS_ANYCAST_*`, so intercepted
    VIPs may appear only as `ip daddr <VIP> ... jump <chain>`, while `dnat to`
    lives inside the target chain or one more jump away. Sticky set elements are
    intentionally ignored because only `daddr` capture rules are considered.
    """
    tables = _index_nft_chains(ruleset_text)
    correlated = []
    seen = set()

    for table_name, chains in tables.items():
        chain_backends = {
            chain_name: [target for line in lines for target in _extract_nft_dnat_targets(line)]
            for chain_name, lines in chains.items()
        }

        def reachable_backends(start_chain: str, max_depth: int = 2) -> list[dict]:
            queue = [(start_chain, 0)]
            visited = set()
            found = []
            found_keys = set()

            while queue:
                chain_name, depth = queue.pop(0)
                if chain_name in visited:
                    continue
                visited.add(chain_name)

                for backend in chain_backends.get(chain_name, []):
                    key = (backend["backend_ip"], backend["backend_port"])
                    if key not in found_keys:
                        found_keys.add(key)
                        found.append(backend)

                if depth >= max_depth:
                    continue

                for line in chains.get(chain_name, []):
                    for next_chain in _extract_nft_jump_targets(line):
                        if next_chain in chains and next_chain not in visited:
                            queue.append((next_chain, depth + 1))

            return found

        for capture_chain, lines in chains.items():
            for line in lines:
                jump_targets = _extract_nft_jump_targets(line)
                if not jump_targets:
                    continue

                capture_dests = _extract_nft_capture_destinations(line)
                if not capture_dests:
                    continue

                proto = "unknown"
                if re.search(r'\btcp\s+dport\b|\bmeta\s+l4proto\s+tcp\b', line):
                    proto = "tcp"
                elif re.search(r'\budp\s+dport\b|\bmeta\s+l4proto\s+udp\b', line):
                    proto = "udp"

                counter_match = re.search(r'counter packets (\d+) bytes (\d+)', line)
                packets = int(counter_match.group(1)) if counter_match else 0
                bytes_val = int(counter_match.group(2)) if counter_match else 0

                for target_chain in jump_targets:
                    backends = reachable_backends(target_chain)
                    if not backends:
                        continue

                    for dest_ip in capture_dests:
                        for backend in backends:
                            key = (
                                table_name,
                                capture_chain,
                                target_chain,
                                dest_ip,
                                backend["backend_ip"],
                                backend["backend_port"],
                                proto,
                            )
                            if key in seen:
                                continue
                            seen.add(key)
                            correlated.append({
                                "backend_ip": backend["backend_ip"],
                                "backend_port": backend["backend_port"],
                                "dest_ip": dest_ip,
                                "dest_ips": [dest_ip],
                                "protocol": proto,
                                "packets": packets,
                                "bytes": bytes_val,
                                "chain": target_chain,
                                "capture_chain": capture_chain,
                                "table": table_name,
                                "raw_rule": line[:200],
                                "discovery": "daddr_jump_dnat",
                            })

    return correlated


def _discover_nft_anycast() -> dict:
    """
    Parse nftables ruleset for DNS anycast/intercepted-VIP defines and references.

    Many real deployments define intercepted VIPs in a top-level variable
    (e.g. `define DNS_ANYCAST_IPV4 = { 4.2.2.5, ... }`) and reference it from
    capture chains via `ip daddr $DNS_ANYCAST_IPV4` while the actual `dnat to`
    sits in separate action chains. Per-rule parsing in `discover_dnat_rules`
    misses these VIPs because the literal IPs never appear next to `dnat to`.

    Returns:
      {
        "anycast_ipv4": set[str],     # IPs from `define DNS_ANYCAST_IPV4`
        "anycast_ipv6": set[str],     # IPs from `define DNS_ANYCAST_IPV6`
        "ref_v4": bool,               # rule references $DNS_ANYCAST_IPV4
        "ref_v6": bool,               # rule references $DNS_ANYCAST_IPV6
      }
    """
    out = {
        "anycast_ipv4": set(),
        "anycast_ipv6": set(),
        "ref_v4": False,
        "ref_v6": False,
    }
    r = _safe_run("nft", ["list", "ruleset"], timeout=10, use_privilege=True)
    if r["exit_code"] != 0:
        return out
    text = r.get("stdout", "") or ""

    # `define NAME = { v1, v2, ... }` may span multiple lines until the closing `}`.
    for m in re.finditer(
        r"define\s+(DNS_ANYCAST_IPV[46])\s*=\s*\{([^}]*)\}",
        text,
        re.IGNORECASE | re.DOTALL,
    ):
        name = m.group(1).upper()
        body = m.group(2)
        ips = [tok.strip() for tok in re.split(r"[,\s]+", body) if tok.strip()]
        target = "anycast_ipv4" if name.endswith("IPV4") else "anycast_ipv6"
        for ip in ips:
            # accept literal v4 or v6 only (skip comments / variables)
            if re.fullmatch(r"\d+\.\d+\.\d+\.\d+", ip):
                if target == "anycast_ipv4":
                    out["anycast_ipv4"].add(ip)
            elif ":" in ip and re.fullmatch(r"[0-9A-Fa-f:]+", ip):
                if target == "anycast_ipv6":
                    out["anycast_ipv6"].add(ip)

    if re.search(r"\$DNS_ANYCAST_IPV4\b", text):
        out["ref_v4"] = True
    if re.search(r"\$DNS_ANYCAST_IPV6\b", text):
        out["ref_v6"] = True
    return out


# ── Sticky set discovery ────────────────────────────────────


def discover_sticky_sets() -> list[dict]:
    """
    Discover dynamic sticky/affinity sets from nftables.
    Name-agnostic: detects by set flags (dynamic, timeout) not by name.
    """
    result = _safe_run("nft", ["-j", "list", "sets"], timeout=10, use_privilege=True)
    sets = []

    if result["exit_code"] != 0:
        # Fallback: parse text output
        return _discover_sticky_sets_text()

    try:
        data = json.loads(result["stdout"])
    except (json.JSONDecodeError, ValueError):
        return _discover_sticky_sets_text()

    nftables = data.get("nftables", [])
    for item in nftables:
        set_def = item.get("set")
        if not set_def:
            continue

        flags = set_def.get("flags", [])
        is_dynamic = "dynamic" in flags
        has_timeout = "timeout" in set_def
        set_type = set_def.get("type", "")

        # Dynamic sets with timeout or sets containing IP type → likely sticky
        if not (is_dynamic or has_timeout):
            continue

        # Check if the type involves IP addresses
        type_involves_ip = False
        if isinstance(set_type, str):
            type_involves_ip = "ipv4_addr" in set_type or "ipv6_addr" in set_type
        elif isinstance(set_type, list):
            type_involves_ip = any("ipv4_addr" in t or "ipv6_addr" in t for t in set_type)

        if not type_involves_ip:
            continue

        elem = set_def.get("elem", [])
        elements = []
        for e in elem:
            if isinstance(e, dict):
                val = e.get("elem", {})
                if isinstance(val, dict) and "val" in val:
                    elements.append(str(val["val"]))
                else:
                    elements.append(str(e))
            else:
                elements.append(str(e))

        sets.append({
            "name": set_def.get("name", ""),
            "table": set_def.get("table", ""),
            "family": set_def.get("family", ""),
            "flags": flags,
            "timeout": set_def.get("timeout"),
            "type": set_type,
            "element_count": len(elem),
            "elements_sample": elements[:10],
            "is_dynamic": is_dynamic,
        })

    return sets


def _discover_sticky_sets_text() -> list[dict]:
    """Fallback: discover sticky sets from text nft output."""
    result = _safe_run("nft", ["list", "sets"], timeout=10, use_privilege=True)
    if result["exit_code"] != 0:
        return []

    sets = []
    current_set = ""
    current_flags = []
    current_timeout = ""
    in_set = False

    for line in result["stdout"].split("\n"):
        stripped = line.strip()

        set_match = re.match(r'set\s+(\S+)\s*\{', stripped)
        if set_match:
            current_set = set_match.group(1)
            current_flags = []
            current_timeout = ""
            in_set = True
            continue

        if in_set:
            if "flags" in stripped:
                current_flags = [f.strip() for f in stripped.split("flags")[1].strip().split(",")]
            if "timeout" in stripped and "=" not in stripped:
                parts = stripped.split()
                for i, p in enumerate(parts):
                    if p == "timeout" and i + 1 < len(parts):
                        current_timeout = parts[i + 1]
            if stripped == "}":
                if "dynamic" in current_flags or current_timeout:
                    sets.append({
                        "name": current_set,
                        "flags": current_flags,
                        "timeout": current_timeout,
                        "is_dynamic": "dynamic" in current_flags,
                    })
                in_set = False

    return sets


# ── DNS listeners discovery ─────────────────────────────────


def discover_dns_listeners() -> list[dict]:
    """Discover all IPs listening on port 53 via ss."""
    result = _safe_run("ss", ["-tulnp"], timeout=5)
    listeners = []

    if result["exit_code"] != 0:
        return listeners

    port53_ips = set()
    for line in result["stdout"].split("\n"):
        if ":53 " not in line and ":53\t" not in line:
            continue
        parts = line.split()
        for part in parts:
            if ":53" in part:
                ip = part.rsplit(":", 1)[0]
                if ip.startswith("["):
                    ip = ip[1:-1]
                if ip in ("*", "0.0.0.0", "::"):
                    continue
                port53_ips.add(ip)

    for ip in sorted(port53_ips):
        listeners.append({"ip": ip, "port": 53})

    return listeners


# ── Full inventory snapshot ─────────────────────────────────


def _discover_hostname() -> str:
    """Read system hostname (read-only)."""
    result = _safe_run("hostname", [], timeout=5)
    if result["exit_code"] == 0 and result["stdout"].strip():
        return result["stdout"].strip()
    result = _safe_run("cat", ["/etc/hostname"], timeout=5)
    if result["exit_code"] == 0 and result["stdout"].strip():
        return result["stdout"].strip()
    return ""


def _discover_network() -> dict:
    """
    Discover host network: default-route interface, primary IPv4/IPv6 and gateways.
    Pure read-only via `ip` commands.
    """
    net = {
        "main_interface": "",
        "ipv4_address": "",
        "ipv4_gateway": "",
        "ipv6_address": "",
        "ipv6_gateway": "",
    }

    # IPv4 default route → interface + gateway
    r4 = _safe_run("ip", ["-j", "-4", "route", "show", "default"], timeout=5)
    iface = ""
    if r4["exit_code"] == 0 and r4["stdout"].strip():
        try:
            routes = json.loads(r4["stdout"])
            if routes:
                iface = routes[0].get("dev", "") or ""
                net["ipv4_gateway"] = routes[0].get("gateway", "") or ""
        except (json.JSONDecodeError, ValueError):
            pass
    if not iface:
        rt = _safe_run("ip", ["route", "show", "default"], timeout=5)
        if rt["exit_code"] == 0:
            m = re.search(r"default\s+via\s+(\S+)\s+dev\s+(\S+)", rt["stdout"])
            if m:
                net["ipv4_gateway"] = net["ipv4_gateway"] or m.group(1)
                iface = m.group(2)
    net["main_interface"] = iface

    # IPv6 default route → gateway (interface usually same)
    r6 = _safe_run("ip", ["-j", "-6", "route", "show", "default"], timeout=5)
    if r6["exit_code"] == 0 and r6["stdout"].strip():
        try:
            routes6 = json.loads(r6["stdout"])
            if routes6:
                net["ipv6_gateway"] = routes6[0].get("gateway", "") or ""
                if not iface:
                    iface = routes6[0].get("dev", "") or ""
                    net["main_interface"] = iface
        except (json.JSONDecodeError, ValueError):
            pass

    # Addresses on the main interface
    if iface:
        ra = _safe_run("ip", ["-j", "addr", "show", "dev", iface], timeout=5)
        if ra["exit_code"] == 0 and ra["stdout"].strip():
            try:
                data = json.loads(ra["stdout"])
                if data:
                    for addr in data[0].get("addr_info", []):
                        fam = addr.get("family")
                        local = addr.get("local", "")
                        prefix = addr.get("prefixlen", "")
                        scope = addr.get("scope", "")
                        if fam == "inet" and local and not net["ipv4_address"]:
                            net["ipv4_address"] = f"{local}/{prefix}" if prefix != "" else local
                        elif fam == "inet6" and local and scope == "global" and not net["ipv6_address"]:
                            net["ipv6_address"] = f"{local}/{prefix}" if prefix != "" else local
            except (json.JSONDecodeError, ValueError):
                pass

    return net


# ── FRR / OSPF discovery ────────────────────────────────────


def discover_frr_config() -> dict:
    """
    Read-only discovery of the running FRR configuration.

    Source of truth: /etc/frr/frr.conf (preferred). Falls back to
    `vtysh -c "show running-config"` when the file is unavailable.

    Extracts: router_id, area, networks announced, per-interface OSPF cost,
    route-maps (name + set metric / set ip next-hop / set metric-type), and
    OSPF-enabled interfaces. This function NEVER mutates FRR state.
    """
    text = ""
    src = None
    r = _safe_run("cat", ["/etc/frr/frr.conf"], timeout=5)
    if r["exit_code"] == 0 and r.get("stdout"):
        text = r["stdout"]
        src = "file"
    else:
        rv = _safe_run("vtysh", ["-c", "show running-config"], timeout=10, use_privilege=True)
        if rv["exit_code"] == 0 and rv.get("stdout"):
            text = rv["stdout"]
            src = "vtysh"

    out: dict = {
        "available": bool(text),
        "source": src,
        "router_id": "",
        "area": "",
        "networks": [],
        "interfaces": [],          # [{name, cost, network_type, ipv6_ospf:{area,cost,network_type}}]
        "default_cost": None,
        "route_maps": [],          # [{name, action, seq, set_metric, set_metric_type, set_ip_next_hop}]
        "redistribute_connected": False,
        "ospfd_enabled": None,
        # New: OSPF6 + segment-routing presence (read from real frr.conf).
        "ipv6_ospf_enabled": False,
        "segment_routing": False,
        "traffic_eng": False,
    }
    if not text:
        # Check daemons file for ospfd flag even when frr.conf is empty
        rd = _safe_run("cat", ["/etc/frr/daemons"], timeout=5)
        if rd["exit_code"] == 0:
            m = re.search(r"^\s*ospfd\s*=\s*(yes|no)\b", rd["stdout"], re.MULTILINE)
            if m:
                out["ospfd_enabled"] = (m.group(1) == "yes")
            m6 = re.search(r"^\s*ospf6d\s*=\s*(yes|no)\b", rd["stdout"], re.MULTILINE)
            if m6:
                out["ipv6_ospf_enabled"] = (m6.group(1) == "yes")
        return out

    # daemons file (independent of frr.conf)
    rd = _safe_run("cat", ["/etc/frr/daemons"], timeout=5)
    if rd["exit_code"] == 0:
        m = re.search(r"^\s*ospfd\s*=\s*(yes|no)\b", rd["stdout"], re.MULTILINE)
        if m:
            out["ospfd_enabled"] = (m.group(1) == "yes")
        m6 = re.search(r"^\s*ospf6d\s*=\s*(yes|no)\b", rd["stdout"], re.MULTILINE)
        if m6:
            # daemons file is a hint; frr.conf ipv6 ospf6 lines override below
            out["ipv6_ospf_enabled"] = out["ipv6_ospf_enabled"] or (m6.group(1) == "yes")

    lines = text.split("\n")
    current_block = None       # "interface:<name>", "router_ospf", "route_map:<name>:<seq>", "segment_routing"
    iface_data: dict = {}
    cost_values: list = []

    for raw in lines:
        line = raw.rstrip()
        stripped = line.strip()
        if not stripped or stripped.startswith("!"):
            continue

        if stripped == "exit" or stripped == "exit-address-family":
            current_block = None
            continue

        m = re.match(r"^interface\s+(\S+)", stripped)
        if m:
            current_block = f"interface:{m.group(1)}"
            iface_data.setdefault(m.group(1), {
                "name": m.group(1),
                "cost": None,
                "network_type": None,
                "ipv6_ospf": None,  # {area, cost, network_type}
            })
            continue

        if stripped == "router ospf" or stripped.startswith("router ospf "):
            current_block = "router_ospf"
            continue

        if stripped == "segment-routing":
            current_block = "segment_routing"
            out["segment_routing"] = True
            continue

        m = re.match(r"^route-map\s+(\S+)\s+(permit|deny)\s+(\d+)", stripped)
        if m:
            name, action, seq = m.group(1), m.group(2), int(m.group(3))
            current_block = f"route_map:{name}:{seq}"
            out["route_maps"].append({
                "name": name,
                "action": action,
                "seq": seq,
                "set_metric": None,
                "set_metric_type": None,
                "set_ip_next_hop": None,
            })
            continue

        # Inside blocks
        if current_block and current_block.startswith("interface:"):
            iname = current_block.split(":", 1)[1]
            mc = re.match(r"^ip\s+ospf\s+cost\s+(\d+)$", stripped)
            if mc:
                c = int(mc.group(1))
                iface_data[iname]["cost"] = c
                cost_values.append(c)
                continue
            mn = re.match(r"^ip\s+ospf\s+network\s+(\S+)$", stripped)
            if mn:
                iface_data[iname]["network_type"] = mn.group(1)
                continue
            # IPv6 OSPF6 per-interface directives
            m6a = re.match(r"^ipv6\s+ospf6\s+area\s+(\S+)$", stripped)
            if m6a:
                v6 = iface_data[iname].get("ipv6_ospf") or {}
                v6["area"] = m6a.group(1)
                iface_data[iname]["ipv6_ospf"] = v6
                out["ipv6_ospf_enabled"] = True
                continue
            m6c = re.match(r"^ipv6\s+ospf6\s+cost\s+(\d+)$", stripped)
            if m6c:
                v6 = iface_data[iname].get("ipv6_ospf") or {}
                v6["cost"] = int(m6c.group(1))
                iface_data[iname]["ipv6_ospf"] = v6
                out["ipv6_ospf_enabled"] = True
                continue
            m6n = re.match(r"^ipv6\s+ospf6\s+network\s+(\S+)$", stripped)
            if m6n:
                v6 = iface_data[iname].get("ipv6_ospf") or {}
                v6["network_type"] = m6n.group(1)
                iface_data[iname]["ipv6_ospf"] = v6
                out["ipv6_ospf_enabled"] = True
                continue

        if current_block == "router_ospf":
            m = re.match(r"^ospf\s+router-id\s+(\S+)$", stripped)
            if m:
                out["router_id"] = m.group(1)
                continue
            if stripped == "redistribute connected":
                out["redistribute_connected"] = True
                continue
            m = re.match(r"^network\s+(\S+)\s+area\s+(\S+)$", stripped)
            if m:
                out["networks"].append({"network": m.group(1), "area": m.group(2)})
                if not out["area"]:
                    out["area"] = m.group(2)
                continue

        if current_block == "segment_routing":
            if stripped == "traffic-eng" or stripped.startswith("traffic-eng "):
                out["traffic_eng"] = True
                continue

        if current_block and current_block.startswith("route_map:"):
            rm = out["route_maps"][-1]
            m = re.match(r"^set\s+metric\s+(\S+)$", stripped)
            if m:
                try:
                    rm["set_metric"] = int(m.group(1))
                except ValueError:
                    rm["set_metric"] = m.group(1)
                continue
            m = re.match(r"^set\s+metric-type\s+(\S+)$", stripped)
            if m:
                rm["set_metric_type"] = m.group(1)
                continue
            m = re.match(r"^set\s+ip\s+next-hop\s+(\S+)$", stripped)
            if m:
                rm["set_ip_next_hop"] = m.group(1)
                continue

    out["interfaces"] = list(iface_data.values())
    if cost_values:
        # mode (most common) as the representative default cost
        from collections import Counter
        out["default_cost"] = Counter(cost_values).most_common(1)[0][0]

    return out



def discover_security_profile() -> dict:
    """
    Detect security profile from live nftables ruleset.

    Criterion (matches the generator at nftables_generator.py: legacy mode does
    NOT emit any `filter` table): presence of `table ip filter` or
    `table ip6 filter` ⇒ 'isp-hardened'; absence ⇒ 'legacy'.

    Read-only — only inspects `nft list ruleset` output.
    """
    out = {
        "profile": "legacy",
        "filter_table_present": False,
        "rate_limit_present": False,
    }
    result = _safe_run("nft", ["list", "ruleset"], timeout=10, use_privilege=True)
    if result["exit_code"] != 0:
        return out

    text = result["stdout"] or ""
    # Match `table ip filter {` / `table ip6 filter {` (top-level filter tables).
    if re.search(r'^\s*table\s+ip6?\s+filter\s*\{', text, re.MULTILINE):
        out["filter_table_present"] = True
        out["profile"] = "isp-hardened"
        # Heuristic: rate limit / anti-amplification when `limit rate` shows up.
        if re.search(r'\blimit\s+rate\b', text):
            out["rate_limit_present"] = True
    return out


def get_full_inventory() -> dict:

    """
    Build a complete runtime inventory of the DNS infrastructure.
    This is the observed-mode equivalent of deploy-state.json.
    """
    instances = discover_unbound_instances()
    vips = discover_vips()
    dnat_rules = discover_dnat_rules()
    sticky_sets = discover_sticky_sets()
    listeners = discover_dns_listeners()

    # Correlate: which VIPs map to which backends via DNAT
    vip_backend_map = {}
    for rule in dnat_rules:
        for dest_ip in rule.get("dest_ips", []):
            if dest_ip not in vip_backend_map:
                vip_backend_map[dest_ip] = []
            vip_backend_map[dest_ip].append({
                "backend_ip": rule["backend_ip"],
                "backend_port": rule["backend_port"],
                "protocol": rule["protocol"],
                "packets": rule["packets"],
                "bytes": rule["bytes"],
            })

    # Classify each VIP by capture mode based on DNAT correlation
    dnat_dest_ips = set()
    for rule in dnat_rules:
        for dest_ip in rule.get("dest_ips", []):
            if dest_ip:
                dnat_dest_ips.add(dest_ip)
        if rule.get("dest_ip"):
            dnat_dest_ips.add(rule["dest_ip"])

    # Anycast VIPs declared via `define DNS_ANYCAST_IPV4/IPV6` and referenced
    # by capture chains (`ip daddr $DNS_ANYCAST_IPV4`). When such an indirection
    # exists AND we discovered any `dnat to <backend>` action, treat every IP in
    # the define as a DNAT-captured VIP. Backends for these VIPs are the union
    # of all discovered DNAT backends (action chain → backend correlation is
    # not 1:1 in nftables, so we expose the full pool).
    anycast = _discover_nft_anycast()
    anycast_dnat_ips: set = set()
    if dnat_rules:
        if anycast["ref_v4"] and anycast["anycast_ipv4"]:
            anycast_dnat_ips |= anycast["anycast_ipv4"]
        if anycast["ref_v6"] and anycast["anycast_ipv6"]:
            anycast_dnat_ips |= anycast["anycast_ipv6"]

    if anycast_dnat_ips:
        # Backend pool: unique (backend_ip, backend_port, protocol) tuples.
        backend_pool: list = []
        seen_pool: set = set()
        for rule in dnat_rules:
            key = (rule.get("backend_ip"), rule.get("backend_port"), rule.get("protocol"))
            if key in seen_pool or not rule.get("backend_ip"):
                continue
            seen_pool.add(key)
            backend_pool.append({
                "backend_ip": rule["backend_ip"],
                "backend_port": rule.get("backend_port", 53),
                "protocol": rule.get("protocol", "unknown"),
                "packets": rule.get("packets", 0),
                "bytes": rule.get("bytes", 0),
            })
        for ip in anycast_dnat_ips:
            dnat_dest_ips.add(ip)
            vip_backend_map.setdefault(ip, list(backend_pool))

        # Ensure anycast VIPs appear in `vips` even if not on a loopback.
        existing_vip_ips = {v.get("ip") for v in vips}
        for ip in anycast_dnat_ips:
            if ip not in existing_vip_ips:
                vips.append({
                    "ip": ip,
                    "prefixlen": 128 if ":" in ip else 32,
                    "interface": "anycast-define",
                    "label": "DNS_ANYCAST",
                })

    # Runtime-expanded nftables rules may expose intercepted VIPs only as
    # `ip daddr <VIP> ... jump <chain>` with `dnat to` inside that target chain.
    # Ensure those daddr-captured VIPs are present even when they are not bound
    # on loopback. Sticky set elements are not included in dnat_dest_ips because
    # they are never parsed as capture destinations.
    existing_vip_ips = {v.get("ip") for v in vips}
    for ip in sorted(dnat_dest_ips):
        if ip and ip not in existing_vip_ips:
            vips.append({
                "ip": ip,
                "prefixlen": 128 if ":" in ip else 32,
                "interface": "nft-capture",
                "label": "nft daddr capture",
            })
            existing_vip_ips.add(ip)

    for vip in vips:
        if vip.get("ip") in dnat_dest_ips:
            vip["capture_mode"] = "dnat"
        else:
            vip["capture_mode"] = "local_bind"

    frr_config = discover_frr_config()

    return {
        "collected_at": datetime.now(timezone.utc).isoformat(),
        "hostname": _discover_hostname(),
        "network": _discover_network(),
        "instances": instances,
        "vips": vips,
        "dnat_rules": dnat_rules,
        "sticky_sets": sticky_sets,
        "listeners": listeners,
        "vip_backend_map": vip_backend_map,
        "frr": frr_config,
        "instance_count": len(instances),
        "vip_count": len(vips),
        "dnat_rule_count": len(dnat_rules),
        "listener_count": len(listeners),
    }


# ── Sync to dns_instances table ─────────────────────────────


def sync_instances_to_db(db) -> dict:
    """
    Discover unbound instances from runtime and sync to dns_instances table.
    Creates missing instances, updates existing ones.
    Does NOT delete instances that are no longer running (they may be temporarily stopped).
    Returns summary of changes.
    """
    from app.models.operational import DnsInstance, InstanceState

    discovered = discover_unbound_instances()
    created = 0
    updated = 0
    unchanged = 0

    for inst in discovered:
        name = inst["instance_name"]
        existing = db.query(DnsInstance).filter(DnsInstance.instance_name == name).first()

        if existing:
            # Update bind_ip, control_port if changed
            changed = False
            if existing.bind_ip != inst["bind_ip"]:
                existing.bind_ip = inst["bind_ip"]
                changed = True
            if existing.control_port != inst["control_port"]:
                existing.control_port = inst["control_port"]
                changed = True
            if inst["outgoing_ip"] and existing.outgoing_ip != inst["outgoing_ip"]:
                existing.outgoing_ip = inst["outgoing_ip"]
                changed = True
            if changed:
                existing.updated_at = datetime.now(timezone.utc)
                updated += 1
            else:
                unchanged += 1
        else:
            # Create new instance
            new_inst = DnsInstance(
                instance_name=name,
                bind_ip=inst["bind_ip"],
                bind_port=inst["bind_port"],
                outgoing_ip=inst["outgoing_ip"],
                control_port=inst["control_port"],
                node_name="local",
                is_enabled=True,
            )
            db.add(new_inst)
            db.flush()

            # Create initial state
            state = InstanceState(
                instance_id=new_inst.id,
                current_status="healthy",
                in_rotation=True,
            )
            db.add(state)
            created += 1

    db.commit()

    return {
        "discovered": len(discovered),
        "created": created,
        "updated": updated,
        "unchanged": unchanged,
        "instances": [i["instance_name"] for i in discovered],
    }
