"""
DNS Control — Runtime Inventory Service
Discovers infrastructure from the running system without depending on
naming conventions or deploy artifacts generated by the DNS Control wizard.

Sources:
  - systemctl: discover unbound instances
  - /etc/unbound/*.conf: extract bind IPs, control interfaces/ports
  - ip -j addr show: discover VIPs on loopback
  - nft -j list ruleset: discover DNAT rules and sticky sets
  - ss -tulnp: discover DNS listeners

This service is the foundation of "observed" mode, allowing the dashboard
to function on manually configured hosts.
"""

import json
import re
import logging
from datetime import datetime, timezone

from app.executors.command_runner import run_command

logger = logging.getLogger("dns-control.runtime-inventory")


def _safe_run(executable: str, args: list[str], timeout: int = 10, use_privilege: bool = False) -> dict:
    try:
        return run_command(executable, args, timeout=timeout, use_privilege=use_privilege)
    except Exception as e:
        logger.debug(f"Command {executable} failed: {e}")
        return {"exit_code": -1, "stdout": "", "stderr": str(e), "duration_ms": 0}


# ── Unbound instance discovery ──────────────────────────────


def discover_unbound_instances() -> list[dict]:
    """
    Discover ALL unbound instances from systemd (running or loaded).
    For each, parse config to extract bind IPs, control interface/port.
    Returns list of dicts compatible with dns_instances table schema.
    """
    result = _safe_run(
        "systemctl", ["list-units", "--all", "--type=service", "--no-pager", "--plain"],
        timeout=10,
    )
    instances = []
    if result["exit_code"] != 0:
        return instances

    for line in result["stdout"].split("\n"):
        if "unbound" not in line or ".service" not in line:
            continue
        name = line.split()[0].replace(".service", "").lstrip("●").strip()
        if name == "unbound":
            continue  # Skip generic service

        is_running = "running" in line or ("active" in line and "inactive" not in line)
        config = _parse_unbound_config(name)

        instances.append({
            "instance_name": name,
            "bind_ips": config["bind_ips"],
            "bind_ip": config["bind_ips"][0] if config["bind_ips"] else "127.0.0.1",
            "bind_port": config["port"],
            "control_interface": config["control_interface"],
            "control_port": config["control_port"],
            "outgoing_ips": config["outgoing_ips"],
            "outgoing_ip": config["outgoing_ips"][0] if config["outgoing_ips"] else None,
            "is_running": is_running,
            "config_path": config["config_path"],
        })

    return instances


def _parse_unbound_config(instance_name: str) -> dict:
    """Parse unbound config for bind IPs, control interface/port, outgoing IPs."""
    config_path = f"/etc/unbound/{instance_name}.conf"
    result = _safe_run("cat", [config_path], timeout=5)

    config = {
        "bind_ips": [],
        "port": 53,
        "control_interface": "127.0.0.1",
        "control_port": 8953,
        "outgoing_ips": [],
        "config_path": config_path,
    }

    if result["exit_code"] != 0:
        return config

    for line in result["stdout"].split("\n"):
        stripped = line.strip()
        if stripped.startswith("#"):
            continue

        if stripped.startswith("interface:") and not stripped.startswith("interface-automatic"):
            ip = stripped.split(":", 1)[1].strip()
            # Handle interface with port: 10.0.0.1@5353
            if "@" in ip:
                parts = ip.split("@")
                ip = parts[0]
                try:
                    config["port"] = int(parts[1])
                except ValueError:
                    pass
            if ip and not ip.startswith("#"):
                config["bind_ips"].append(ip)

        elif stripped.startswith("port:"):
            try:
                config["port"] = int(stripped.split(":", 1)[1].strip())
            except ValueError:
                pass

        elif stripped.startswith("control-interface:"):
            config["control_interface"] = stripped.split(":", 1)[1].strip()

        elif stripped.startswith("control-port:"):
            try:
                config["control_port"] = int(stripped.split(":", 1)[1].strip())
            except ValueError:
                pass

        elif stripped.startswith("outgoing-interface:"):
            ip = stripped.split(":", 1)[1].strip()
            if ip:
                config["outgoing_ips"].append(ip)

    if not config["bind_ips"]:
        config["bind_ips"] = ["127.0.0.1"]

    return config


# ── VIP discovery from loopback ─────────────────────────────


def discover_vips() -> list[dict]:
    """
    Discover VIPs from loopback interfaces (lo, lo0, lo:*, dummy*).
    Returns IPs with /32 mask that are not 127.0.0.1.
    """
    result = _safe_run("ip", ["-j", "addr", "show"], timeout=5)
    vips = []

    if result["exit_code"] != 0:
        return vips

    try:
        interfaces = json.loads(result["stdout"])
    except (json.JSONDecodeError, ValueError):
        return vips

    for iface in interfaces:
        ifname = iface.get("ifname", "")
        # Include loopback and dummy interfaces
        if not (ifname == "lo" or ifname.startswith("lo") or ifname.startswith("dummy")):
            continue

        for addr in iface.get("addr_info", []):
            if addr.get("family") != "inet":
                continue
            ip = addr.get("local", "")
            prefixlen = addr.get("prefixlen", 0)
            if ip == "127.0.0.1":
                continue
            if ip:
                vips.append({
                    "ip": ip,
                    "prefixlen": prefixlen,
                    "interface": ifname,
                    "label": addr.get("label", ifname),
                })

    return vips


# ── DNAT discovery from nftables ────────────────────────────


def discover_dnat_rules() -> list[dict]:
    """
    Discover all DNAT rules from nftables ruleset.
    Name-agnostic: detects by 'dnat to' keyword, not chain names.
    Also detects vmap-based DNAT (numgen ... vmap { ... } dnat).
    Returns list of DNAT mappings with counters.
    """
    result = _safe_run("nft", ["list", "ruleset"], timeout=10, use_privilege=True)
    if result["exit_code"] != 0:
        logger.warning(f"nft list ruleset failed (exit={result['exit_code']}): {result.get('stderr', '')[:200]}")
        return []

    rules = []
    current_chain = ""
    current_table = ""

    for line in result["stdout"].split("\n"):
        stripped = line.strip()

        table_match = re.match(r'table\s+(\S+)\s+(\S+)\s*\{', stripped)
        if table_match:
            current_table = f"{table_match.group(1)} {table_match.group(2)}"
            continue

        chain_match = re.match(r'chain\s+(\S+)\s*\{', stripped)
        if chain_match:
            current_chain = chain_match.group(1)
            continue

        if "dnat" not in stripped:
            continue

        # Extract counters (present on both simple and vmap rules)
        counter_match = re.search(r'counter packets (\d+) bytes (\d+)', stripped)
        packets = int(counter_match.group(1)) if counter_match else 0
        bytes_val = int(counter_match.group(2)) if counter_match else 0

        # Extract destination IP (VIP) from the rule
        dest_ip = None
        dest_match = re.search(r'ip\s+daddr\s+(\d+\.\d+\.\d+\.\d+)', stripped)
        if dest_match:
            dest_ip = dest_match.group(1)
        dest_set_match = re.search(r'ip\s+daddr\s+\{([^}]+)\}', stripped)
        dest_ips = []
        if dest_set_match:
            dest_ips = [ip.strip() for ip in dest_set_match.group(1).split(",") if ip.strip()]

        # Detect protocol
        proto = "unknown"
        if re.search(r'\btcp\s+dport\b|\bmeta\s+l4proto\s+tcp\b', stripped):
            proto = "tcp"
        elif re.search(r'\budp\s+dport\b|\bmeta\s+l4proto\s+udp\b', stripped):
            proto = "udp"

        # Pattern 1: simple "dnat to IP:PORT"
        dnat_match = re.search(r'dnat to (\d+\.\d+\.\d+\.\d+)(?::(\d+))?', stripped)
        if dnat_match:
            backend_ip = dnat_match.group(1)
            backend_port = int(dnat_match.group(2)) if dnat_match.group(2) else 53
            rules.append({
                "backend_ip": backend_ip,
                "backend_port": backend_port,
                "dest_ip": dest_ip,
                "dest_ips": dest_ips if dest_ips else ([dest_ip] if dest_ip else []),
                "protocol": proto,
                "packets": packets,
                "bytes": bytes_val,
                "chain": current_chain,
                "table": current_table,
                "raw_rule": stripped[:200],
            })
            continue

        # Pattern 2: vmap-based DNAT "dnat to ... vmap { 0 : IP, 1 : IP }"
        # or "numgen ... vmap { 0 : IP:PORT, ... }"
        vmap_match = re.search(r'vmap\s*\{([^}]+)\}', stripped)
        if vmap_match and "dnat" in stripped:
            vmap_content = vmap_match.group(1)
            for entry in vmap_content.split(","):
                entry = entry.strip()
                ip_match = re.search(r'(\d+\.\d+\.\d+\.\d+)(?::(\d+))?', entry)
                if ip_match:
                    backend_ip = ip_match.group(1)
                    backend_port = int(ip_match.group(2)) if ip_match.group(2) else 53
                    rules.append({
                        "backend_ip": backend_ip,
                        "backend_port": backend_port,
                        "dest_ip": dest_ip,
                        "dest_ips": dest_ips if dest_ips else ([dest_ip] if dest_ip else []),
                        "protocol": proto,
                        "packets": packets,
                        "bytes": bytes_val,
                        "chain": current_chain,
                        "table": current_table,
                        "raw_rule": stripped[:200],
                    })

    logger.info(f"DNAT discovery: found {len(rules)} rules")
    return rules


# ── Sticky set discovery ────────────────────────────────────


def discover_sticky_sets() -> list[dict]:
    """
    Discover dynamic sticky/affinity sets from nftables.
    Name-agnostic: detects by set flags (dynamic, timeout) not by name.
    """
    result = _safe_run("nft", ["-j", "list", "sets"], timeout=10, use_privilege=True)
    sets = []

    if result["exit_code"] != 0:
        # Fallback: parse text output
        return _discover_sticky_sets_text()

    try:
        data = json.loads(result["stdout"])
    except (json.JSONDecodeError, ValueError):
        return _discover_sticky_sets_text()

    nftables = data.get("nftables", [])
    for item in nftables:
        set_def = item.get("set")
        if not set_def:
            continue

        flags = set_def.get("flags", [])
        is_dynamic = "dynamic" in flags
        has_timeout = "timeout" in set_def
        set_type = set_def.get("type", "")

        # Dynamic sets with timeout or sets containing IP type → likely sticky
        if not (is_dynamic or has_timeout):
            continue

        # Check if the type involves IP addresses
        type_involves_ip = False
        if isinstance(set_type, str):
            type_involves_ip = "ipv4_addr" in set_type or "ipv6_addr" in set_type
        elif isinstance(set_type, list):
            type_involves_ip = any("ipv4_addr" in t or "ipv6_addr" in t for t in set_type)

        if not type_involves_ip:
            continue

        elem = set_def.get("elem", [])
        elements = []
        for e in elem:
            if isinstance(e, dict):
                val = e.get("elem", {})
                if isinstance(val, dict) and "val" in val:
                    elements.append(str(val["val"]))
                else:
                    elements.append(str(e))
            else:
                elements.append(str(e))

        sets.append({
            "name": set_def.get("name", ""),
            "table": set_def.get("table", ""),
            "family": set_def.get("family", ""),
            "flags": flags,
            "timeout": set_def.get("timeout"),
            "type": set_type,
            "element_count": len(elem),
            "elements_sample": elements[:10],
            "is_dynamic": is_dynamic,
        })

    return sets


def _discover_sticky_sets_text() -> list[dict]:
    """Fallback: discover sticky sets from text nft output."""
    result = _safe_run("nft", ["list", "sets"], timeout=10, use_privilege=True)
    if result["exit_code"] != 0:
        return []

    sets = []
    current_set = ""
    current_flags = []
    current_timeout = ""
    in_set = False

    for line in result["stdout"].split("\n"):
        stripped = line.strip()

        set_match = re.match(r'set\s+(\S+)\s*\{', stripped)
        if set_match:
            current_set = set_match.group(1)
            current_flags = []
            current_timeout = ""
            in_set = True
            continue

        if in_set:
            if "flags" in stripped:
                current_flags = [f.strip() for f in stripped.split("flags")[1].strip().split(",")]
            if "timeout" in stripped and "=" not in stripped:
                parts = stripped.split()
                for i, p in enumerate(parts):
                    if p == "timeout" and i + 1 < len(parts):
                        current_timeout = parts[i + 1]
            if stripped == "}":
                if "dynamic" in current_flags or current_timeout:
                    sets.append({
                        "name": current_set,
                        "flags": current_flags,
                        "timeout": current_timeout,
                        "is_dynamic": "dynamic" in current_flags,
                    })
                in_set = False

    return sets


# ── DNS listeners discovery ─────────────────────────────────


def discover_dns_listeners() -> list[dict]:
    """Discover all IPs listening on port 53 via ss."""
    result = _safe_run("ss", ["-tulnp"], timeout=5)
    listeners = []

    if result["exit_code"] != 0:
        return listeners

    port53_ips = set()
    for line in result["stdout"].split("\n"):
        if ":53 " not in line and ":53\t" not in line:
            continue
        parts = line.split()
        for part in parts:
            if ":53" in part:
                ip = part.rsplit(":", 1)[0]
                if ip.startswith("["):
                    ip = ip[1:-1]
                if ip in ("*", "0.0.0.0", "::"):
                    continue
                port53_ips.add(ip)

    for ip in sorted(port53_ips):
        listeners.append({"ip": ip, "port": 53})

    return listeners


# ── Full inventory snapshot ─────────────────────────────────


def get_full_inventory() -> dict:
    """
    Build a complete runtime inventory of the DNS infrastructure.
    This is the observed-mode equivalent of deploy-state.json.
    """
    instances = discover_unbound_instances()
    vips = discover_vips()
    dnat_rules = discover_dnat_rules()
    sticky_sets = discover_sticky_sets()
    listeners = discover_dns_listeners()

    # Correlate: which VIPs map to which backends via DNAT
    vip_backend_map = {}
    for rule in dnat_rules:
        for dest_ip in rule.get("dest_ips", []):
            if dest_ip not in vip_backend_map:
                vip_backend_map[dest_ip] = []
            vip_backend_map[dest_ip].append({
                "backend_ip": rule["backend_ip"],
                "backend_port": rule["backend_port"],
                "protocol": rule["protocol"],
                "packets": rule["packets"],
                "bytes": rule["bytes"],
            })

    # Also check VIPs on loopback that appear in DNAT dest
    for vip in vips:
        ip = vip["ip"]
        if ip not in vip_backend_map:
            # Check if this VIP appears as a jump target destination
            for rule in dnat_rules:
                if not rule.get("dest_ips"):
                    # Rule without explicit dest_ip might be in a VIP-specific chain
                    pass

    return {
        "collected_at": datetime.now(timezone.utc).isoformat(),
        "instances": instances,
        "vips": vips,
        "dnat_rules": dnat_rules,
        "sticky_sets": sticky_sets,
        "listeners": listeners,
        "vip_backend_map": vip_backend_map,
        "instance_count": len(instances),
        "vip_count": len(vips),
        "dnat_rule_count": len(dnat_rules),
        "listener_count": len(listeners),
    }


# ── Sync to dns_instances table ─────────────────────────────


def sync_instances_to_db(db) -> dict:
    """
    Discover unbound instances from runtime and sync to dns_instances table.
    Creates missing instances, updates existing ones.
    Does NOT delete instances that are no longer running (they may be temporarily stopped).
    Returns summary of changes.
    """
    from app.models.operational import DnsInstance, InstanceState

    discovered = discover_unbound_instances()
    created = 0
    updated = 0
    unchanged = 0

    for inst in discovered:
        name = inst["instance_name"]
        existing = db.query(DnsInstance).filter(DnsInstance.instance_name == name).first()

        if existing:
            # Update bind_ip, control_port if changed
            changed = False
            if existing.bind_ip != inst["bind_ip"]:
                existing.bind_ip = inst["bind_ip"]
                changed = True
            if existing.control_port != inst["control_port"]:
                existing.control_port = inst["control_port"]
                changed = True
            if inst["outgoing_ip"] and existing.outgoing_ip != inst["outgoing_ip"]:
                existing.outgoing_ip = inst["outgoing_ip"]
                changed = True
            if changed:
                existing.updated_at = datetime.now(timezone.utc)
                updated += 1
            else:
                unchanged += 1
        else:
            # Create new instance
            new_inst = DnsInstance(
                instance_name=name,
                bind_ip=inst["bind_ip"],
                bind_port=inst["bind_port"],
                outgoing_ip=inst["outgoing_ip"],
                control_port=inst["control_port"],
                node_name="local",
                is_enabled=True,
            )
            db.add(new_inst)
            db.flush()

            # Create initial state
            state = InstanceState(
                instance_id=new_inst.id,
                current_status="healthy",
                in_rotation=True,
            )
            db.add(state)
            created += 1

    db.commit()

    return {
        "discovered": len(discovered),
        "created": created,
        "updated": updated,
        "unchanged": unchanged,
        "instances": [i["instance_name"] for i in discovered],
    }
