import { useState } from 'react';

const generatedFiles = [
  {
    path: '/etc/unbound/unbound01.conf',
    content: `server:
  interface: 100.126.255.101
  port: 53
  outgoing-interface: 45.232.215.16
  num-threads: 4
  msg-cache-size: 256m
  rrset-cache-size: 512m
  key-cache-size: 256m
  cache-min-ttl: 60
  cache-max-ttl: 86400
  do-ip4: yes
  do-ip6: no
  do-udp: yes
  do-tcp: yes
  access-control: 0.0.0.0/0 allow
  root-hints: "/usr/share/dns/root.hints"
  hide-identity: yes
  hide-version: yes
  harden-glue: yes
  harden-dnssec-stripped: yes
  use-caps-for-id: yes
  prefetch: yes
  
remote-control:
  control-enable: yes
  control-port: 8953
  control-interface: 127.0.0.1`,
  },
  {
    path: '/etc/nftables.conf',
    content: `#!/usr/sbin/nft -f
flush ruleset

table ip nat {
  chain prerouting {
    type nat hook prerouting priority -100; policy accept;
    ip daddr 4.2.2.5 udp dport 53 numgen inc mod 4 map {
      0 : dnat to 100.126.255.101,
      1 : dnat to 100.126.255.102,
      2 : dnat to 100.126.255.103,
      3 : dnat to 100.126.255.104
    }
    ip daddr 4.2.2.5 tcp dport 53 numgen inc mod 4 map {
      0 : dnat to 100.126.255.101,
      1 : dnat to 100.126.255.102,
      2 : dnat to 100.126.255.103,
      3 : dnat to 100.126.255.104
    }
  }
  chain postrouting {
    type nat hook postrouting priority 100; policy accept;
    masquerade
  }
}

table ip filter {
  chain input {
    type filter hook input priority 0; policy drop;
    ct state established,related accept
    iif lo accept
    udp dport 53 accept
    tcp dport 53 accept
    tcp dport 8443 accept
    ip protocol ospf accept
    drop
  }
}`,
  },
  {
    path: '/etc/frr/frr.conf',
    content: `frr version 10.2
frr defaults traditional
hostname dns-rec-01
!
router ospf
 ospf router-id 172.28.22.6
 redistribute connected
 network 172.28.22.4/30 area 0.0.0.0
!
interface lo0
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
!
interface enp6s18
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ip ospf cost 10
!
line vty
!`,
  },
  {
    path: '/etc/network/post-up.sh',
    content: `#!/bin/bash
# Generated by DNS Control
# Post-up script for dummy interface and IPs

ip link add lo0 type dummy 2>/dev/null || true
ip link set lo0 up

# VIP Anycast
ip addr replace 4.2.2.5/32 dev lo0

# Unbound bind IPs
ip addr replace 100.126.255.101/32 dev lo0
ip addr replace 100.126.255.102/32 dev lo0
ip addr replace 100.126.255.103/32 dev lo0
ip addr replace 100.126.255.104/32 dev lo0

# Public exit IPs
ip addr replace 45.232.215.16/32 dev lo0
ip addr replace 45.232.215.17/32 dev lo0
ip addr replace 45.232.215.18/32 dev lo0
ip addr replace 45.232.215.19/32 dev lo0`,
  },
  {
    path: '/etc/systemd/system/unbound01.service',
    content: `[Unit]
Description=Unbound DNS resolver (instance 01)
After=network.target

[Service]
Type=notify
ExecStart=/usr/sbin/unbound -d -c /etc/unbound/unbound01.conf
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target`,
  },
];

export default function FilesPage() {
  const [selected, setSelected] = useState(generatedFiles[0].path);
  const file = generatedFiles.find(f => f.path === selected);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold">Arquivos Gerados</h1>
        <p className="text-sm text-muted-foreground">Visualize os arquivos de configuração</p>
      </div>

      <div className="flex flex-wrap gap-2">
        {generatedFiles.map(f => (
          <button
            key={f.path}
            onClick={() => setSelected(f.path)}
            className={`px-3 py-1.5 text-xs font-mono rounded border transition-colors ${
              selected === f.path
                ? 'bg-primary/15 text-primary border-primary/30'
                : 'bg-secondary text-secondary-foreground border-border hover:bg-secondary/80'
            }`}
          >
            {f.path.split('/').pop()}
          </button>
        ))}
      </div>

      {file && (
        <div className="noc-panel">
          <div className="flex items-center justify-between mb-2">
            <span className="font-mono text-sm text-muted-foreground">{file.path}</span>
            <button className="px-2.5 py-1 text-xs bg-secondary text-secondary-foreground rounded border border-border hover:bg-secondary/80">
              Exportar
            </button>
          </div>
          <pre className="terminal-output max-h-[500px]">{file.content}</pre>
        </div>
      )}
    </div>
  );
}
